# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
import random
import string

class Ui_mainWindow(object):
    def alertBox(self,title,message):
        window = QtWidgets.QMessageBox()
        window.setWindowTitle(title)
        window.setText(message)
        window.setStandardButtons(QtWidgets.QMessageBox.Ok)
        window.exec_()
    def generateRandomPassword(self):
        if self.PassLimit.text() == "":
            self.alertBox('Blank Message','Please enter your password limit')
        else:
            num = int(self.PassLimit.text())
            password = ""
            for n in range(num):
                limit = random.randint(1,90)
                password = password + string.printable[limit]
            self.PassLimit.clear()
            return self.Output.setText(password)

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(640, 480)
        mainWindow.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color:white;\n"
"border-radius:8px\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AppTitle = QtWidgets.QLabel(self.centralwidget)
        self.AppTitle.setGeometry(QtCore.QRect(90, 30, 461, 61))
        self.AppTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Copperplate Gothic Bold\";\n"
"")
        self.AppTitle.setObjectName("AppTitle")
        self.PassLimit = QtWidgets.QLineEdit(self.centralwidget)
        self.PassLimit.setGeometry(QtCore.QRect(170, 200, 321, 51))
        self.PassLimit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"MV Boli\";\n"
"padding:8px;\n"
"border:2px solid white;\n"
"border-radius: 8px;")
        self.PassLimit.setText("")
        self.PassLimit.setObjectName("PassLimit")
        self.PassTitle = QtWidgets.QLabel(self.centralwidget)
        self.PassTitle.setGeometry(QtCore.QRect(170, 120, 321, 61))
        self.PassTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Copperplate Gothic Bold\";\n"
"")
        self.PassTitle.setObjectName("PassTitle")
        self.PassLimit.setValidator(QIntValidator(1,999))
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.generateRandomPassword)
        self.pushButton.setGeometry(QtCore.QRect(170, 280, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setMouseTracking(False)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 174, 44);\n"
"padding:8px;\n"
"font: 12pt \"Copperplate Gothic Bold\";\n"
"border:2px solid white;\n"
"border-radius: 8px;")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.Output = QtWidgets.QLineEdit(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(170, 360, 321, 51))
        self.Output.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"MV Boli\";\n"
"padding:8px;\n"
"border:2px solid white;\n"
"border-radius: 8px;")
        self.Output.setText("")
        self.Output.setObjectName("Output")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Random Password Generator"))
        self.AppTitle.setText(_translate("mainWindow", "Random Password Generator "))
        self.PassTitle.setText(_translate("mainWindow", " Enter your password limit"))
        self.pushButton.setText(_translate("mainWindow", "Generate Password "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
